module.exports = {
  columns: {
    units: 'B',
    expected: 'C',
    low: 'D',
    high: 'E',
    std: 'F',
    distribution: 'G',
    correlation: 'H',
    notes: 'I',
    distribution_alt: 'M',
    correlation_alt: 'N',
  },
  rows: { // index
    caloric_intake: 4,
    protein_vegetal_intake: 5,
    protein_animal_intake: 6,
    N_content_protein: 8,
    P_content_protein_vegetal: 9,
    P_content_protein_animal: 10,
    K_content_caloric_intake: 11,
    N_excretion: 13,
    P_excretion: 14,
    K_excretion: 15,
    energy_excretion: 16,
    N_in_urine: 18,
    P_in_urine: 19,
    K_in_urine: 20,
    energy_in_urine: 21,
    N_in_feces: 23,
    P_in_feces: 24,
    K_in_feces: 25,
    energy_in_feces: 26,
    N_reduced_inorganic_in_urine: 28,
    N_reduced_inorganic_in_feces: 29,
    urine_excretion: 31,
    feces_excretion: 32,
    urine_moisture_content: 34,
    feces_moisture_content: 35,
    Mg_in_urine: 37,
    Mg_in_feces: 38,
    Ca_in_urine: 40,
    Ca_in_feces: 41,
    // general global parameters
    maximum_methane_emission: 44,
    time_full_degradation: 45,
    reduction_full_degradation: 46,
    N2O_GWP: 47,
    CH4_GWP: 48,
    exchange_rate: 49,
    discount_rate: 50,
  },
}
