module.exports = {
  columns: {
    units: 'B',
    expected: 'C',
    low: 'D',
    high: 'E',
    std: 'F',
    distribution: 'G',
    correlation: 'H',
    notes: 'I',
    distribution_alt: 'M',
    correlation_alt: 'N',
  },
  rows: { // index
    mixed_excreta_module: 2,
    urine_module: 4,
    feces_module: 5,
    // tanker_truck_parameters
    losses_tanker_truck: 8,
    N_loss_tanker_truck: 9,
    P_loss_tanker_truck: 10,
    K_loss_tanker_truck: 11,
    Mg_loss_tanker_truck: 12,
    Ca_loss_tanker_truck: 13,
    C_loss_tanker_truck: 14,
    transport_distance_tanker_truck: 15,
    transport_emissions_factor_tanker_truck: 16,
    truck_emptying_cost_1: 17,
    truck_emptying_cost_2: 18,
    truck_emptying_cost_3: 19,
    truck_emptying_cost_4: 20,
    truck_emptying_capacity_1: 21,
    truck_emptying_capacity_2: 22,
    truck_emptying_capacity_3: 23,
    truck_emptying_capacity_4: 24,
    truck_emptying_add_fee_percentage: 25,
    // handcart_and_truck_parameters
    losses_handcart_and_truck: 28,
    N_loss_handcart_and_truck: 29,
    P_loss_handcart_and_truck: 30,
    K_loss_handcart_and_truck: 31,
    Mg_loss_handcart_and_truck: 32,
    Ca_loss_handcart_and_truck: 33,
    C_loss_handcart_and_truck: 34,
    transport_distance_CBS_truck: 35,
    transport_emissions_factor_CBS_truck: 36,
    emptying_cost_CBS_handcart: 37,
    transport_cost_CBS_truck: 38,
  },
}
